name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check go mod tidy
      run: go mod tidy -diff

    - name: Run go vet
      run: go vet .

    - name: Run go test
      run: go test -race -v -cover -vet=off .
